/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'coupang' at '14. 10. 20 오전 9:33' with Gradle 1.9
 *
 * @author coupang, @date 14. 10. 20 오전 9:33
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
